name = "chf-ic"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "IC"

[blocks.options.export_array_ascii]
block = "options"
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
reader = "urword"
optional = true
mf6internal = "export_ascii"
longname = "export array variables to layered ascii files."
type = "keyword"

[blocks.griddata.strt]
shape = "(nodes)"
block = "griddata"
description = "is the initial (starting) stage---that is, stage at the beginning of the CHF Model simulation.  STRT must be specified for all CHF Model simulations. One value is read for every model reach."
default = "0.0"
reader = "readarray"
layered = true
longname = "starting concentration"
type = "double"
