__author__ = "Joseph D. Hughes"
__date__ = "Jun 23, 2025"
__version__ = "1.8.0.dev0"
__maintainer__ = "Joseph D. Hughes"
__email__ = "jdhughes@usgs.gov"
__status__ = "Production"
__description__ = """Python tools for MODFLOW development and testing."""
