__author__ = "Joseph D. Hughes"
__date__ = "Apr 20, 2026"
__version__ = "1.9.2"
__maintainer__ = "Joseph D. Hughes"
__email__ = "jdhughes@usgs.gov"
__status__ = "Production"
__description__ = """Python tools for MODFLOW development and testing."""
