// Base grammar with common rules for all MF6 components

array_format: ("constant" | "internal" | "external" | "open/close") word*
array_data: ([WS] (NUMBER | word)+ _NL+)*

recarray_line: [WS] recarray_item* _NL+
recarray_item: NUMBER | word

word: /[a-zA-Z0-9._'~,-\\(\\)]+/
_block_index: INT

%import common.NEWLINE -> _NL
%import common.WS
%import common.WS_INLINE
%import common.CNAME
%import common.NUMBER
%import common.INT
%import common.SH_COMMENT
%ignore WS_INLINE
%ignore SH_COMMENT